### ISSUE TITLE
Detect when command have been executed from the menu

### ISSUE THREAD

**Issue by Tazaf** [lenneTech/gluegun-menu#1]
Hi 👋 

I'd like to be able to process my commands differently when the've been launched from the menu than when they've been directly typed and executed by the user (for example by prompting them with some options), and I don't think there is currently a way to detect this in your plugin.

I think adding a special option the `toolbox.parameters.options` object would do the trick, without much side effects.

Something like the following [at the line 104 of your `menu.extension.ts` file](https://github.com/lenneTech/gluegun-menu/blob/master/src/extensions/menu.extension.ts#L104):

```ts
// Run command
try {
  this.toolbox.parameters.options.fromGluegunMenu = true; // <-- 
  await command.run(this.toolbox);
  process.exit();
} catch (e) {
  // ...
}
```
A new method could be added to the `GluegunMenuToolbox` (or in the `Menu` class) that would abstract this underlying mechanism and provide a straightforward way to branch conditionnaly in our code based on how the command has been executed, like this:

```ts
toolbox.fromMenu = () => {
  return toolbox.parameters.options.fromGlueguneMenu;
}
```

Then in the command:

```ts
if (toolbox.fromMenu()) {
  // Do something based on that info
}
```

What do you think about that? Would this be something you'd consider adding to this (otherwise excellent) plugin?

**Comment by kaihaase** [comment]
Hello @Tazaf , thank you very much for your great suggestion. I have integrated it into version 0.0.2.
